### ISSUE TITLE
Node version 10 is end of life

### ISSUE THREAD

**Issue by polymike** [binxio/azure-devops-extensions#41]
Azure pipeline is warning that the Node version used by the installer is end of life. Can it be updated (to 18 or 20)

`##[warning]Task 'Google Cloud SDK tool installer' version 0 (GoogleCloudSdkInstaller@0) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance`

**Comment by WimDiepgrond** [comment]
Same warning here

**Comment by laurensknoll** [comment]
Thanks for raising the issue.  I'll prepare an extension update to the current LTS node runtime(s).

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by laurensknoll** [comment]
Node20 support is included as of the following extension versions:
- Google Cloud SDK 0.3.17
- Google Cloud Auth 0.0.7

As it's a minor update the "end of life runtime"-warning should disappear automatically due to an auto-upgrade.

**Comment by polymike** [comment]
Thankyou
