### ISSUE TITLE
License required

### ISSUE THREAD

**Issue by arvindkrbhatt** [binxio/azure-devops-extensions#6]
Hi Laurens Knoll,
Can you please upload valid license for binxio/azure-devops-extensions project? so that we can use it in our official instance of Azure as plugins.

Regards
arvind

**Comment by mvanholsteijn** [comment]
We added a Apache 2 license to the repo. Does that solve the issue?

**Comment by laurensknoll** [comment]
@arvindkrbhatt I've just published the extension with an apache 2 license. Let me know if you need any other help to start using the extension.

**Comment by arvindkrbhatt** [comment]
Thanks Laurens for quick response. Let me check with Operation team if they are OK with this. I'll revert soon.
